server:
  port: 9005
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
spring:
  application:
    name: admin-server
  boot:
    admin:
      context-path: /sba
      notify:
        mail:
          enabled: true
          to: jiangjie@smartcloudgis.com
          from: jiangjie@smartcloudgis.com
          ignore-changes: UNKNOWN:UP,UNKNOWN:OFFLINE,OFFLINE:UP
#          ignore-changes: UNKNOWN:UP
          #ignore-changes: - "*:UP" #从任何状态到up状态都不要发邮件通知

      routes:
        endpoints: env,metrics,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,loggers,auditevents,hystrix.stream
      turbine:
        clusters: default
        #,unieap-eureka-server-single
        location: turbine
  mail:
    host: smtp.exmail.qq.com
    username: jiangjie@smartcloudgis.com
    password: PbfE2aUaWY8GSZzL
    properties:
        mail.debug: false
        mail.smtp.auth : true
        mail.smtp.port: 465
        mail.smtp.ssl.enable: true
        mail.smtp.ssl.socketFactory: sf
        mail.smtp.timeout : 2000
        mail.smtp.starttls.enable : true
        mail.smtp.starttls.required : true
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone:  http://127.0.0.1:9000/eureka  #http://130.75.131.241:8761/eureka,http://130.75.131.248:8762/eureka
      #http://134.224.249.33:1111/eureka/  正式库
      #http://134.224.249.33:1111/eureka/  测试库
      #http://127.0.0.1:8761/eureka,http://127.0.0.1:8762/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.instance_id:${server.port}}
    #instance-id: ${spring.application.name}:${docker.ipAddress}:${spring.application.instance_id:${server.port}}
    lease-renewal-interval-in-seconds: 5  #每隔几秒告诉eureka服务器我还存活，用于心跳检测
    lease-expiration-duration-in-seconds: 10 #如果心跳检测一直没有发送，10秒后会从eureka服务器中将此服务剔除
