spring:
    application:
        name: eureka-client
    http:
        encoding:
            charset: utf8
            force: true
            enabled: true
server:
    port: 9210
    tomcat:
        uri-encoding: UTF-8
#    servlet:
#        context-path: /client
management:
    endpoint:
        shutdown: true
eureka:
    client:
        healthcheck:
            enabled: true
        instance-info-replication-interval-seconds: 10
        serviceUrl:
            defaultZone: http://127.0.0.1:9000/eureka
    instance:
        prefer-ip-address: true
        instance-id: ${spring.cloud.client.ip-address}:${spring.application.instance_id:${server.port}}
        lease-renewal-interval-in-seconds: 5
        lease-expiration-duration-in-seconds: 15
        #注册实例文档
        status-page-url: http://${spring.cloud.client.ip-address}:${server.port}/swagger-ui.html
logging:
    level:
        root: INFO
        org.hibernate: INFO
        org.hibernate.type.descriptor.sql.BasicBinder: TRACE
        org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
        com.neusoft: DEBUG
        com.netflix: DEBUG
